apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80


        # resource:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    #       # 1000m =1